spring.application.name=app

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/proyectodesarrollo
spring.datasource.username=postgres
spring.datasource.password=75133907
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Encoding UTF-8 para soportar caracteres especiales (ñ, tildes, etc.)
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.mandatory-file-encoding=UTF-8
